# Example secrets configuration
# Copy this file to secrets.yaml and fill in your values
# DO NOT commit secrets.yaml to version control!

# API Keys (if needed)
# openai_api_key: "your-api-key-here"
# anthropic_api_key: "your-api-key-here"

# Model paths (if using local models)
# local_model_path: "/path/to/your/model"

# Database connections (if needed)
# db_connection_string: "postgresql://user:pass@host:port/db"